// Code generated by "stringer -type=Class"; DO NOT EDIT.

package gc

import "strconv"

const _Class_name = "PxxxPEXTERNPAUTOPAUTOHEAPPPARAMPPARAMOUTPFUNCPDISCARD"

func (i Class) String(pstate *PackageState) string {
	if i >= Class(len(pstate._Class_index)-1) {
		return "Class(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Class_name[pstate._Class_index[i]:pstate._Class_index[i+1]]
}
