package objabi

const (
	PCDATA_StackMapIndex       = 0
	PCDATA_InlTreeIndex        = 1
	PCDATA_RegMapIndex         = 2
	FUNCDATA_ArgsPointerMaps   = 0
	FUNCDATA_LocalsPointerMaps = 1
	FUNCDATA_InlTree           = 2
	FUNCDATA_RegPointerMaps    = 3

	// ArgsSizeUnknown is set in Func.argsize to mark all functions
	// whose argument size is unknown (C vararg functions, and
	// assembly code without an explicit specification).
	// This value is generated by the compiler, assembler, or linker.
	ArgsSizeUnknown = -0x80000000
)
