// Code generated by "stringer -type Operator -linecomment"; DO NOT EDIT.

package syntax

import "strconv"

const _Operator_name = ":!<-||&&==!=<<=>>=+-|^*/%&&^<<>>"

func (i Operator) String(pstate *PackageState) string {
	i -= 1
	if i >= Operator(len(pstate._Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Operator_name[pstate._Operator_index[i]:pstate._Operator_index[i+1]]
}
