// Code generated by "stringer -type token -linecomment"; DO NOT EDIT.

package syntax

import "strconv"

const _token_name = "EOFnameliteralopop=opop=:=<-*([{)]},;:....breakcasechanconstcontinuedefaultdeferelsefallthroughforfuncgogotoifimportinterfacemappackagerangereturnselectstructswitchtypevar"

func (i token) String(pstate *PackageState) string {
	i -= 1
	if i >= token(len(pstate._token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[pstate._token_index[i]:pstate._token_index[i+1]]
}
